stages:
  - test-ui
  - test-api
  - test-performance
  - test-security
  - report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

# ===== UI Selenium Tests =====
ui-tests:
  stage: test-ui
  image: selenium/standalone-chrome:latest
  script:
    - echo "Running Selenium UI tests in headless Chrome"
    - mvn clean test -Dtest=Scenario1_Autocomplete,Scenario2_Form,Scenario3_Alerts,Scenario4_Buttons,Scenario5_Navigation
  artifacts:
    when: always
    paths:
      - src/main/java/com/formy/target/surefire-reports/
    expire_in: 1 week

# ===== API Postman Tests =====
api-tests:
  stage: test-api
  image: postman/newman:latest
  script:
    - echo "Running Postman API tests"
    - newman run api/postman/reqres-collection.json -r cli,htmlextra --reporter-htmlextra-export newman/report.html
  artifacts:
    when: always
    paths:
      - newman/
    expire_in: 1 week

# ===== Performance Tests (JMeter) =====
performance-tests:
  stage: test-performance
  image: justb4/jmeter:5.5
  script:
    - mkdir -p performance-results
    - jmeter -n -t performance/performance_test.jmx -l performance-results/results.jtl -j performance-results/jmeter.log
  artifacts:
    when: always
    paths:
      - performance-results/
    expire_in: 1 week
  only:
    - main

# ===== Security Tests (OWASP ZAP) =====
security-tests:
  stage: test-security
  image: owasp/zap2docker-stable
  script:
    - mkdir -p security-results
    - zap-baseline.py -t https://formy-project.herokuapp.com -r security-results/zap-report.html -w security-results/zap-report.md || true
  artifacts:
    when: always
    paths:
      - security-results/
    expire_in: 1 week
  allow_failure: true

# ===== Consolidated Report & Notification =====
generate-report:
  stage: report
  image: alpine:latest
  script:
    - echo "📊 GENERATING COMBINED REPORTS"
    - echo "✅ Selenium UI Tests reports: src/main/java/com/formy/target/surefire-reports/"
    - echo "✅ Postman API Tests report: newman/report.html"
    - echo "✅ Performance Tests report: performance-results/"
    - echo "✅ Security Tests report: security-results/"
    - echo "🎉 PIPELINE CI/CD FINISHED SUCCESSFULLY"
  artifacts:
    when: always
    paths:
      - src/main/java/com/formy/target/surefire-reports/
      - newman/
      - performance-results/
      - security-results/
    expire_in: 1 month
  dependencies:
    - ui-tests
    - api-tests
    - performance-tests
    - security-tests
